package usecase

import (
	"context"
	"errors"
	"strings"

	"gladiatortravel/internal/model"
	"gladiatortravel/internal/repository"
)

type Service struct {
	repo *repository.PostgresRepository
}

func NewService(repo *repository.PostgresRepository) *Service {
	return &Service{repo: repo}
}

func (s *Service) Health(ctx context.Context) error {
	return s.repo.Health(ctx)
}

func (s *Service) ListDestinations(ctx context.Context, sortBy string, minScore float64) ([]model.Destination, error) {
	return s.repo.ListDestinations(ctx, sortBy, minScore)
}

func (s *Service) ListVenues(ctx context.Context, destinationID int64, venueType string, openLate *bool, priceTier *int) ([]model.Venue, error) {
	return s.repo.ListVenues(ctx, destinationID, venueType, openLate, priceTier)
}

func (s *Service) ListAccommodations(ctx context.Context, destinationID int64, _ string) ([]model.Accommodation, error) {
	return s.repo.ListAccommodations(ctx, destinationID)
}

func (s *Service) ListTravelOptions(ctx context.Context, destinationID int64, originCity string) ([]model.TravelOption, error) {
	return s.repo.ListTravelOptions(ctx, destinationID, originCity)
}

func (s *Service) UpsertPreferences(ctx context.Context, p model.UserPreferences) error {
	return s.repo.UpsertPreferences(ctx, p)
}

func (s *Service) AddVenueFeedback(ctx context.Context, userID, venueID int64, feedback string) error {
	feedback = strings.ToLower(feedback)
	if feedback != "up" && feedback != "down" {
		return errors.New("feedback must be up or down")
	}
	return s.repo.AddVenueFeedback(ctx, userID, venueID, feedback)
}

func (s *Service) CreateTrip(ctx context.Context, t model.Trip) (int64, error) {
	return s.repo.CreateTrip(ctx, t)
}

func (s *Service) GenerateItinerary(ctx context.Context, tripID, destinationID int64, days int) error {
	if days < 2 {
		days = 2
	}
	if days > 4 {
		days = 4
	}
	venues, err := s.repo.TopVenuesForDestination(ctx, destinationID)
	if err != nil {
		return err
	}
	if len(venues) < 3 {
		return errors.New("not enough venues to generate itinerary")
	}

	slots := []string{"lunch", "dinner", "bar"}
	var items []model.ItineraryItem
	idx := 0
	for d := 1; d <= days; d++ {
		for _, slot := range slots {
			v := venues[idx%len(venues)]
			items = append(items, model.ItineraryItem{
				DayNumber: d,
				Slot:      slot,
				VenueID:   v.ID,
				Notes:     "auto-generated by GladiatorTravel PoC",
			})
			idx++
		}
	}
	return s.repo.InsertItineraryItems(ctx, tripID, items)
}

func (s *Service) GetItinerary(ctx context.Context, tripID int64) ([]model.ItineraryItem, error) {
	return s.repo.GetItinerary(ctx, tripID)
}
